# Development Environment Configuration
environment: development

# Interactive Brokers connection
ib:
  host: "127.0.0.1"
  port: 7497  # Paper trading port
  client_id: 1

# Use mock data for development
data:
  use_mock: true
  mock_update_rate: 100  # updates per second

# Options screening criteria for development
options:
  screening:
    min_dte: 10
    max_dte: 50
    strike_range_pct: 0.09  # ±9% around ATM
    max_spread_width_pct: 0.10  # ≤10% of mid
    min_mid_price: 0.20  # ≥$0.20
    min_volume: 0  # No volume filter in dev
    min_open_interest: 0  # No OI filter in dev
    symbols: ["SPX", "XSP"]
  
  # Risk-free rate for pricing
  risk_free_rate: 0.05
  
  # Maximum option contracts to subscribe to
  max_contracts: 200

# Reduced limits for testing
strategy:
  filters:
    volume_min: 0  # No volume filter in dev
    oi_min: 0      # No OI filter in dev

risk:
  daily_hard_stop_pct: 10.0  # Higher limit for testing

# Dashboard settings
dashboard:
  host: "127.0.0.1"
  port: 8050
  update_interval: 5  # seconds

monitoring:
  log_level: DEBUG
