# Demo Configuration - Enhanced Mock Data
# Perfect for demonstrations and testing

data_provider:
  type: "mock"
  update_interval: 1.0
  volatility_factor: 1.5  # More dynamic for demo
  
strategy:
  initial_params:
    theta: 0.04    # Long-run variance
    kappa: 2.0     # Mean reversion speed
    xi: 0.3        # Volatility of volatility
    rho: -0.7      # Asset-vol correlation
    v0: 0.04       # Initial variance
  
  calibration_frequency: 300  # 5 minutes
  calibration_method: "least_squares"
  max_calibration_time: 30

mispricing_detection:
  min_mispricing_pct: 5.0
  strong_mispricing_pct: 15.0
  min_signal_confidence: 70.0
  max_signals_per_cycle: 20
  min_option_volume: 10
  min_time_to_expiry: 7

risk_management:
  max_portfolio_delta: 50000.0
  max_position_size: 100
  max_daily_loss: 10000.0
  stop_loss_pct: 0.5
  position_size_method: "kelly"
  risk_free_rate: 0.05

delta_hedging:
  delta_band: 0.05
  hedge_frequency: 60
  hedge_instrument: "SPY"
  account_equity: 1000000.0
  hedge_ratio: 1.0

dashboard:
  port: 8050
  host: "127.0.0.1"
  debug: true
  auto_reload: true
  update_interval: 2

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_handler: true
  log_directory: "logs"
  max_file_size: 10485760
  backup_count: 5